#!/bin/bash

#Depends on scrot, ImageMagick (for "convert" command) and i3lock.

scrot /tmp/screenlock.png
convert /tmp/screenlock.png -blur 0x5 /tmp/screenlockblur.png
i3lock -e -f -i /tmp/screenlockblur.png
rm /tmp/screenlock.png
rm /tmp/screenlockblur.png
exit